### PR TITLE
For practice

### PR DESCRIPTION
**Pull request by katiemsullivan**
I've created a branch for my working changes called "katies_working_branch". You guys should do the same & open PRs that we can all code review.

@aharbert678 @sophyyang @mlarsen3

### CODE REVIEW

**Comment by katiemsullivan** [comment]
+1

**Comment by sophyyang** [comment]
Importing a GitHub project into Eclipse:
1.Fork from Katie's LadyBug Tracker https://github.com/katiemsullivan/LadyBugTracker.git
2.From Eclipse menu (File->Import->Git->Project from Git (with smart import)->Clone URl)

**Comment by sophyyang** [comment]
I got the error "Source folder is not a Java project."

**Comment by katiemsullivan** [comment]
@sophyyang  Can you try File->Import->General->Existing Projects into Workspace ? Let me know if that works :)

**Comment by sophyyang** [comment]
Sorry, it still give me "Source folder is not a Java project" error.

Thanks it works. I added tables document to folder Notes. Could you pull to
your main? Thanks

**Comment by katiemsullivan** [comment]
@sophyyang  Can you open a pull request with your changes? And then I can merge it into master. 

To create a pull request, save your changes locally, commit your changes & push them to your branch on git, and create a new pull request. You'll want to show the difference between master & your branch in the pull request like this:

http://content.screencast.com/users/ksully456/folders/Jing/media/11850701-699e-4f0f-afee-39230139717e/00002110.png

**Comment by sophyyang** [comment]
I think I mess up my github. My localLadyBug project don't let me add a new java class. I have hard time to commit. Last night my eclipse workspace crushed. I tried to save it today, but end up I deleted all my projects. :(

**Comment by katiemsullivan** [comment]
Oh no! That is not good :-1: I think that the commit message you showed me is because your branch needs to be updated with master. I can show you how to do that.

**Pull request merged**
